'''389. Find the Difference'''

'''You are given two strings s and t.

String t is generated by random shuffling string s and then adding one more letter at a random position.

Return the letter that was added in t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
'''



class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        d=""
        for i in range(len(t)):
            if(t[i] not in s):
                d+=t[i]
            else:
                s=s[:s.index(t[i])]+s[s.index(t[i])+1:]
        return d